from .local_config import *

#Databae
SQLALCHEMY_DATABASE_URL = LOCAL_SQLALCHEMY_DATABASE_URL


#JWT
SECRET_KEY = LOCAL_SECRET_KEY
ALGORITHM = LOCAL_ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = LOCAL_ACCESS_TOKEN_EXPIRE_MINUTES


